-- v3.0.0_2 - Catálogo de idiomas y textos i18n
--
-- Recuperado de las migraciones V2.0.0_1/_2/_4 del histórico antiguo, cuyos INSERT estaban
-- intactos aunque el DDL que los acompañaba estuviera corrompido.

INSERT INTO lang (id, name) VALUES ('es', 'Español'), ('en', 'English');

INSERT INTO tag (tag, lang_id, text) VALUES
    ('ACCEPT', 'es', 'Aceptar'),
    ('ALL_MESSAGES_SENT', 'es', 'Se han enviado todos los mensajes.'),
    ('CANCEL', 'es', 'Cancelar'),
    ('ERROR_COMMAND_SHOULD_BE_ON_GROUP', 'es', 'Este comando debe ser enviado en un grupo en el que esté el bot.'),
    ('ERROR_COMMAND_SHOULD_BE_ON_PRIVATE', 'es', 'Este comando debe ser enviado por privado al bot.'),
    ('ERROR_GAME_ALREADY_CREATED', 'es', 'Ya existe un juego activo en este grupo o el creador tiene un juego activo en otro grupo.'),
    ('ERROR_GAME_ALREADY_FILLED', 'es', 'Ya se ha superado el número máximo de jugadores.'),
    ('ERROR_GAME_ALREADY_STARTED', 'es', 'La partida ya está iniciada.'),
    ('ERROR_GAME_DOESNT_EXISTS', 'es', 'No hay ninguna partida iniciada en este grupo.'),
    ('ERROR_GAME_NOT_FILLED', 'es', 'La partida aun no ha llegado al numero mínimo de jugadores.'),
    ('ERROR_GAME_NOT_STARTED', 'es', 'La partida aun no se ha iniciado.'),
    ('ERROR_GAME_ONLY_CREATOR_CAN_CONFIGURE', 'es', 'Solo el creador de la partida puede configurarla.'),
    ('ERROR_GAME_ONLY_CREATOR_CAN_DELETE', 'es', 'Solo el creador de la partida puede borrarla.'),
    ('ERROR_GAME_ONLY_CREATOR_CAN_START', 'es', 'Solo el creador de la partida puede iniciarla.'),
    ('ERROR_GAME_USER_DOESNT_EXISTS', 'es', 'No estas registrado. Escríbeme /start por privado.'),
    ('ERROR_PLAYER_ALREADY_JOINED', 'es', 'Ya estas participando en esta partida.'),
    ('ERROR_PLAYER_ALREADY_PLAYING', 'es', 'Ya estas participando en una partida.'),
    ('ERROR_PLAYER_ALREADY_VOTED_DELETION', 'es', 'Ya has votado para borrar esta partida.'),
    ('ERROR_PLAYER_DOES_NOT_EXISTS', 'es', 'No estas unido a ninguna partida.'),
    ('ERROR_PLAYER_NO_GAMES', 'es', 'No tienes ninguna partida activa.'),
    ('ERROR_UNKNOWN', 'es', 'Error desconocido'),
    ('ERROR_USER_ALREADY_REGISTERED', 'es', 'Ya estas registrado. Consulta /help para mas información.'),
    ('GAME_CHANGE_MAX_N_PLAYERS', 'es', 'Cambiar nº máximo de jugadores'),
    ('GAME_CONFIGURE_BUTTON', 'es', 'Configurar la partida'),
    ('GAME_CREATED_CURRENT_PLAYER_NUMBER', 'es', 'Se han unido estos <b>{0}</b> jugadores:'),
    ('GAME_CREATED_CURRENT_VOTE_DELETION_NUMBER', 'es', '<b>{0}</b> jugador/es han votado borrar la partida.'),
    ('GAME_CREATED_GROUP', 'es', '¡Ya he creado la partida!'),
    ('GAME_CREATING', 'es', 'Un momentito, estoy creando la partida...'),
    ('GAME_DELETED', 'es', 'Se ha borrado la partida.'),
    ('GAME_DELETE_BUTTON', 'es', 'Borrar partida'),
    ('GAME_DELETION_ALL', 'es', 'Se han borrado todas las partidas.'),
    ('GAME_DELETION_FORCED', 'es', 'Lo sentimos. Su partida ha sido borrada por la administración. Puede crear una partida nueva.'),
    ('GAME_DELETION_USER', 'es', 'Se ha borrado la partida de {0}.'),
    ('GAME_HELP', 'es', '	Bienvenido a la ayuda de {0} versión {1}\n\nPuedes consultar la ayuda en el siguiente enlace: {2}\n\nDisfrutad del bot y... ¡A jugar!\n\nCreado por {3}.'),
    ('GAME_JOIN_BUTTON', 'es', 'Unirse a la partida'),
    ('GAME_LEAVE', 'es', 'Dejar la partida'),
    ('GAME_LEFT', 'es', 'Has dejado la partida'),
    ('GAME_SELECTED_MAX_PLAYER_NUMBER', 'es', 'El número máximo de jugadores es <b>{0}</b>.'),
    ('GAME_SELECT_MAX_PLAYERS', 'es', '\nSelecciona nº máximo de jugadores:'),
    ('GAME_START_BUTTON', 'es', 'Iniciar la partida'),
    ('GO_BACK', 'es', '← Volver'),
    ('PLAYER_CREATED_GAME', 'es', 'He creado la partida en el grupo, puedes configurarla allí'),
    ('PLAYER_JOINED', 'es', 'Te has unido a la partida.'),
    ('PLAYER_JOINING', 'es', 'Un momentito, estoy intentando unirte a la partida...'),
    ('PLAYER_VOTED_DELETION', 'es', 'Has votado borrar la partida'),
    ('PLAYER_WELCOME', 'es', '¡Bienvenido! Acabo de añadirte a mi base de datos.\nSiempre que necesites ayuda puedes escribir /help\n¡Gracias por unirte!'),
    ('USER_LANG_CHANGE', 'es', 'Elige tu idioma:'),
    ('USER_LANG_CHANGED', 'es', 'Se ha cambiado el idioma.'),
    ('ACCEPT', 'en', 'Accept'),
    ('ALL_MESSAGES_SENT', 'en', 'All messages sent.'),
    ('CANCEL', 'en', 'Cancel'),
    ('ERROR_COMMAND_SHOULD_BE_ON_GROUP', 'en', 'This command must be sent in a group in which the bot is.'),
    ('ERROR_COMMAND_SHOULD_BE_ON_PRIVATE', 'en', 'This command must be sent privately to the bot.'),
    ('ERROR_GAME_ALREADY_CREATED', 'en', 'There is an active game in this group or the creator has an active game on another group.'),
    ('ERROR_GAME_ALREADY_FILLED', 'en', 'The game has already reached the maximum of players.'),
    ('ERROR_GAME_ALREADY_STARTED', 'en', 'The game has already started.'),
    ('ERROR_GAME_DOESNT_EXISTS', 'en', 'There is no game initiated in this group.'),
    ('ERROR_GAME_NOT_FILLED', 'en', 'The game has not reached the minimum number of players.'),
    ('ERROR_GAME_NOT_STARTED', 'en', 'The game has not started.'),
    ('ERROR_GAME_ONLY_CREATOR_CAN_CONFIGURE', 'en', 'Only the creator can configure it.'),
    ('ERROR_GAME_ONLY_CREATOR_CAN_DELETE', 'en', 'Only the creator can delete it.'),
    ('ERROR_GAME_ONLY_CREATOR_CAN_START', 'en', 'Only the creator can start the game.'),
    ('ERROR_GAME_USER_DOESNT_EXISTS', 'en', 'You are not registered. Input /start in private.'),
    ('ERROR_PLAYER_ALREADY_JOINED', 'en', 'Ya estas participando en esta partida.'),
    ('ERROR_PLAYER_ALREADY_PLAYING', 'en', 'You are already playing a game.'),
    ('ERROR_PLAYER_ALREADY_VOTED_DELETION', 'en', 'You have already voted to delete the game.'),
    ('ERROR_PLAYER_DOES_NOT_EXISTS', 'en', 'You have not joined any game.'),
    ('ERROR_PLAYER_NO_GAMES', 'en', 'You have no active games.'),
    ('ERROR_UNKNOWN', 'en', 'Unknown error.'),
    ('ERROR_USER_ALREADY_REGISTERED', 'en', 'You´re already registered. Write /help for more information.'),
    ('GAME_CHANGE_MAX_N_PLAYERS', 'en', 'Change number of max players.'),
    ('GAME_CONFIGURE_BUTTON', 'en', 'Configure game'),
    ('GAME_CREATED_CURRENT_PLAYER_NUMBER', 'en', '<b>{0}</b> players have joined:'),
    ('GAME_CREATED_CURRENT_VOTE_DELETION_NUMBER', 'en', '<b>{0}</b> player/s have voted to delete the game.'),
    ('GAME_CREATED_GROUP', 'en', 'I already created the game!'),
    ('GAME_CREATING', 'en', 'Hold on, I´m creating the game...'),
    ('GAME_DELETED', 'en', 'Game deleted.'),
    ('GAME_DELETE_BUTTON', 'en', 'Delete game'),
    ('GAME_DELETION_ALL', 'en', 'All games have been deleted.'),
    ('GAME_DELETION_FORCED', 'en', 'Sorry, the game has been deleted by an admin. You can start a new game.'),
    ('GAME_DELETION_USER', 'en', '{0}´s game has been deleted.'),
    ('GAME_HELP', 'en', 'Welcome to the help menu of {0} version {1}\n\nYou can check for help here: {2}\n\nEnjoy the bot and... Let´s play!\n\nMade by {3}.'),
    ('GAME_JOIN_BUTTON', 'en', 'Join game'),
    ('GAME_LEAVE', 'en', 'Leave game'),
    ('GAME_LEFT', 'en', 'You left the game.'),
    ('GAME_SELECTED_MAX_PLAYER_NUMBER', 'en', 'The maximum number of players is <b>{0}</b>.'),
    ('GAME_SELECT_MAX_PLAYERS', 'en', '\nSelect max number of players:'),
    ('GAME_START_BUTTON', 'en', 'Start game'),
    ('GO_BACK', 'en', '← Go back'),
    ('PLAYER_CREATED_GAME', 'en', 'I created a game in the group, you can configure it there.'),
    ('PLAYER_JOINED', 'en', 'You joined the game.'),
    ('PLAYER_JOINING', 'en', 'Hold on, you are joining the game...'),
    ('PLAYER_VOTED_DELETION', 'en', 'You voted to delete the game.'),
    ('PLAYER_WELCOME', 'en', 'Welcome! I just added you to my database.\nWhen you need help you only have to send me the command /help\nThank you for joining!'),
    ('USER_LANG_CHANGE', 'en', 'Choose your language:'),
    ('USER_LANG_CHANGED', 'en', 'Language changed successfully.');
